# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [1]:
nombre = "Milena"
edad = 35

print(f"Hola, me llamo {nombre} y tengo {edad} años.")

Hola, me llamo Milena y tengo 35 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [5]:
numeros = [10, 25, 3, 47, 8, 15]

print("Primer y último elemento de la lista:")
print(numeros[0])
print(numeros[-1])

print("Tres primeros elementos de la lista:")
print(numeros[0:3])

print("Se agrega el número 99 al final de la lista:")
numeros.append(99)
print(numeros)


Primer y último elemento de la lista:
10
15
Tres primeros elementos de la lista:
[10, 25, 3]
Se agrega el número 99 al final de la lista:
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [6]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

if estudiante["promedio"] >= 6.0:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [7]:
def calcular_area(base, altura):
    return base * altura / 2

resultado = calcular_area(base=5, altura=8)
print(resultado)

20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [9]:
cuadrados = [x**2 for x in range(1, 11)]
print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [10]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [11]:
# Arreglo con valores [1.5, 2.5, 3.5, 4.5]
arreglo1 = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo 1:", arreglo1)
print("shape:", arreglo1.shape)
print("dtype:", arreglo1.dtype)

print()

# Matriz de ceros de 3 filas x 4 columnas
arreglo2 = np.zeros((3, 4))
print("Arreglo 2:\n", arreglo2)
print("shape:", arreglo2.shape)
print("dtype:", arreglo2.dtype)

print()

# Arreglo con 6 valores igualmente espaciados entre 0 y 1
arreglo3 = np.linspace(0, 1, 6)
print("Arreglo 3:", arreglo3)
print("shape:", arreglo3.shape)
print("dtype:", arreglo3.dtype)


Arreglo 1: [1.5 2.5 3.5 4.5]
shape: (4,)
dtype: float64

Arreglo 2:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape: (3, 4)
dtype: float64

Arreglo 3: [0.  0.2 0.4 0.6 0.8 1. ]
shape: (6,)
dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [12]:
a = np.arange(1, 13)
matriz = a.reshape(3, 4)
print("Matriz:\n", matriz)

print("Valor máximo:", matriz.max())
print("Valor mínimo:", matriz.min())
print("Posición del máximo:", np.unravel_index(matriz.argmax(), matriz.shape))

Matriz:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Valor máximo: 12
Valor mínimo: 1
Posición del máximo: (np.int64(2), np.int64(3))


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [15]:
a = np.random.randint(1, 21, size=5)
b = np.random.randint(1, 21, size=5)

print("Arreglo a:", a)
print("Arreglo b:", b)
print()
print("Suma:        ", a + b)
print("Resta:       ", a - b)
print("Multiplicación:", a * b)

Arreglo a: [10 16 15 15 19]
Arreglo b: [12 20  3  5 19]

Suma:         [22 36 18 20 38]
Resta:        [-2 -4 12 10  0]
Multiplicación: [120 320  45  75 361]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [17]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

index = notas >= 6
print("Indexación booleana:", index)
print("Notas >= 6:", notas[index])


Indexación booleana: [ True  True  True False  True False  True False]
Notas >= 6: [ 8.5  6.   9.2  7.8 10. ]
